[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"   # safe par défaut

[dev]
  functions = "netlify/functions"

# (Optionnel) Activer la page de succès côté préprod si besoin
# [[redirects]]
#   from = "/success"
#   to = "/success.html"
#   status = 200
