[build]
  publish = "."
  functions = "netlify/functions"

# Planification: exécute la fonction tous les jours à 08:00 UTC
[functions."send-daily-digest"]
  schedule = "0 8 * * *"

# Redirection de /success vers la page HTML de succès
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
